import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { getAuthUser } from "@/lib/actions/user.action";
import Link from "next/link";
import { NavUser } from "@/components/molecules/nav-user";
import { ModeToggle } from "@/components/molecules/theme-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getAuthUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <div className='flex flex-row justify-between px-24 py-5 container mx-auto'>
            <Link href='/private' className='text-xl underline underline-offset-1'>Private Page</Link>
            <NavUser user={user} />
            <ModeToggle />
          </div>
          {children}
        </Provider>
      </body>
    </html>
  );
}
